name: Flutter Build & Upload to Firebase

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Upload APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      # Decode google-services.json using GitHub Secrets
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      # Decode firebase_options.dart
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{ secrets.FIREBASE_OPTION }}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart

      # Set up .env file
      - name: Set up .env file
        run: |
          echo "HOST=${{ secrets.HOST }}" > .env
          # Add any other environment variables if necessary
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      # Set up Flutter (using the latest stable version)
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Install dependencies
      - run: flutter pub get

      # Analyze the Flutter project
      - run: flutter analyze

      # Build the APK
      - run: flutter build apk --release

      # Upload the APK artifact
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      # Upload to Firebase App Distribution
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
